### ISSUE TITLE
Error on joining server

### ISSUE THREAD

**Issue by LLjo** [pitbox46/monetamoney#1]
Got This Error when trying to enter my server.

Using Forge 36.2.0

Some conflict perhaps?

[29Jul2021 00:31:18.552] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 7
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
		2: NORMAL
		3: ASM: class com.legacy.blue_skies.events.SkiesPlayerEvents onAdvancementGranted(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
		4: ASM: class mod.beethoven92.betterendforge.common.event.forge.ForgeEvents giveGuideBookToPlayer(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
		5: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@40caebb0 onAdvancement(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$2777/1648796233@169bd455
		7: ASM: github.pitbox46.monetamoney.ServerEvents@47026c9f onAdvancement(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
java.lang.NullPointerException
	at github.pitbox46.monetamoney.ServerEvents.onAdvancement(ServerEvents.java:122)
	at net.minecraftforge.eventbus.ASMEventHandler_1848_ServerEvents_onAdvancement_AdvancementEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1060)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:213)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35)
	at net.minecraft.advancements.criterion.AbstractCriterionTrigger.func_235959_a_(SourceFile:72)
	at net.minecraft.advancements.criterion.TickTrigger.func_193182_a(SourceFile:21)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:393)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[29Jul2021 00:31:18.564] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID bdb52b8c-126d-4109-a831-d52aa5a36efc
[29Jul2021 00:31:18.575] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NullPointerException
	at github.pitbox46.monetamoney.ServerEvents.onAdvancement(ServerEvents.java:122) ~[monetamoney:1.16.5-1.0.0-SNAP7]
	at net.minecraftforge.eventbus.ASMEventHandler_1848_ServerEvents_onAdvancement_AdvancementEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1060) ~[forge:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:213) ~[?:?]
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35) ~[?:?]
	at net.minecraft.advancements.criterion.AbstractCriterionTrigger.func_235959_a_(SourceFile:72) ~[?:?]
	at net.minecraft.advancements.criterion.TickTrigger.func_193182_a(SourceFile:21) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:393) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more

**Comment by pitbox46** [comment]
I know about this bug and it should be fixed in the next release.
